# Generated by Django 4.0 on 2022-05-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopledata', '0002_criminal_known_delete_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unknown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField(null=True)),
            ],
            options={
                'db_table': 'unknowns',
            },
        ),
    ]
