# Generated by Django 4.0 on 2022-05-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peopledata', '0003_unknown'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unknown',
            table=None,
        ),
    ]
