# Generated by Django 4.0 on 2022-05-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopledata', '0006_alter_unknown_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagefieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='unknownimg')),
            ],
            options={
                'db_table': 'unknowns',
            },
        ),
        migrations.DeleteModel(
            name='Unknown',
        ),
    ]
