# Generated by Django 4.0 on 2022-05-25 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peopledata', '0009_alter_imagefieldmodel_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImagefieldModel',
            new_name='Unknown',
        ),
    ]
