# Generated by Django 4.0 on 2022-05-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopledata', '0010_rename_imagefieldmodel_unknown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unknown',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
